version: "3.9"

services:
  api:
    build: .
    container_name: nest_app
    expose:
      - "3000"
    depends_on:
      - postgres
    env_file:
      - .env
    command: npm run start:prod

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5554:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  pgdata:
